
26-05-2020 10-20-30: Starting game vs AdditionalPylons
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py:307: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x16F02B98>
  _warnings.warn("Unclosed client session {!r}".format(self),
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py:85: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\protocol.py", line 43, in __request
    response_bytes = await self._ws.receive_bytes()
  File "C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client_ws.py", line 281, in receive_bytes
    raise TypeError(
TypeError: Received message 257:None is not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py", line 76, in join_ladder_game
    result = await sc2.main._play_game(players[0], client, realtime, portconfig, step_time_limit, game_time_limit)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\main.py", line 246, in _play_game
    result = await _play_game_ai(client, player_id, player.ai, realtime, step_time_limit, game_time_limit)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\main.py", line 228, in _play_game_ai
    await client.step()
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\client.py", line 141, in step
    return await self._execute(step=sc_pb.RequestStep(count=self.game_step))
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\protocol.py", line 67, in _execute
    response = await self.__request(request)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\protocol.py", line 48, in __request
    sys.exit(2)
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 15, in <module>
    result, opponentid = run_ladder_game(bot)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py", line 67, in run_ladder_game
    result = asyncio.get_event_loop().run_until_complete(g)
  File "C:\Users\Manuel\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py", line 81, in join_ladder_game
    except ConnectionAlreadyClosed:
NameError: name 'ConnectionAlreadyClosed' is not defined

26-05-2020 10-31-46: Starting game vs AdditionalPylons
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py:85: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py:307: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x17145AD8>

26-05-2020 10-56-06: Starting game vs AdditionalPylons
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py:85: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py:307: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x169E4AF0>

26-05-2020 11-08-12: Starting game vs AdditionalPylons
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py:85: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py:307: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x16C70AA8>

26-05-2020 12-10-01: Starting game vs MadAI

26-05-2020 12-14-13: Starting game vs MicroMachine
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py:85: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py:307: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x16B64B68>

26-05-2020 15-28-23: Starting game vs PerfectSplit
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py:85: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py:307: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x17064B08>

26-05-2020 20-41-30: Starting game vs BetterThanNothing

26-05-2020 20-56-36: Starting game vs BetterThanNothing
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py:307: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x17613B98>
  _warnings.warn("Unclosed client session {!r}".format(self),
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py:85: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\protocol.py", line 43, in __request
    response_bytes = await self._ws.receive_bytes()
  File "C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client_ws.py", line 281, in receive_bytes
    raise TypeError(
TypeError: Received message 257:None is not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py", line 76, in join_ladder_game
    result = await sc2.main._play_game(players[0], client, realtime, portconfig, step_time_limit, game_time_limit)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\main.py", line 238, in _play_game
    player_id = await client.join_game(
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\client.py", line 88, in join_game
    result = await self._execute(join_game=req)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\protocol.py", line 67, in _execute
    response = await self.__request(request)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\protocol.py", line 48, in __request
    sys.exit(2)
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 15, in <module>
    result, opponentid = run_ladder_game(bot)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py", line 67, in run_ladder_game
    result = asyncio.get_event_loop().run_until_complete(g)
  File "C:\Users\Manuel\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py", line 81, in join_ladder_game
    except ConnectionAlreadyClosed:
NameError: name 'ConnectionAlreadyClosed' is not defined

26-05-2020 21-00-40: Starting game vs BetterThanNothing
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py:85: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py:307: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x17474B80>

27-05-2020 02-02-19: Starting game vs AdditionalPylons
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py:307: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x17812A78>
  _warnings.warn("Unclosed client session {!r}".format(self),
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py:85: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\protocol.py", line 43, in __request
    response_bytes = await self._ws.receive_bytes()
  File "C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client_ws.py", line 281, in receive_bytes
    raise TypeError(
TypeError: Received message 257:None is not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py", line 76, in join_ladder_game
    result = await sc2.main._play_game(players[0], client, realtime, portconfig, step_time_limit, game_time_limit)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\main.py", line 246, in _play_game
    result = await _play_game_ai(client, player_id, player.ai, realtime, step_time_limit, game_time_limit)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\main.py", line 228, in _play_game_ai
    await client.step()
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\client.py", line 141, in step
    return await self._execute(step=sc_pb.RequestStep(count=self.game_step))
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\protocol.py", line 67, in _execute
    response = await self.__request(request)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\protocol.py", line 48, in __request
    sys.exit(2)
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 15, in <module>
    result, opponentid = run_ladder_game(bot)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py", line 67, in run_ladder_game
    result = asyncio.get_event_loop().run_until_complete(g)
  File "C:\Users\Manuel\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py", line 81, in join_ladder_game
    except ConnectionAlreadyClosed:
NameError: name 'ConnectionAlreadyClosed' is not defined

27-05-2020 08-57-43: Starting game vs PerfectSplit
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py:85: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py:307: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x17474B50>

27-05-2020 09-16-58: Starting game vs MicroMachine
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py:85: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py:307: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x17704AD8>

27-05-2020 09-19-43: Starting game vs Blunty

27-05-2020 09-23-38: Starting game vs Gumbys
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py:85: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py:307: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x17524AA8>

27-05-2020 09-25-10: Starting game vs Rusty
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py:307: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x16A64AA8>
  _warnings.warn("Unclosed client session {!r}".format(self),
ResourceWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py:85: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\protocol.py", line 43, in __request
    response_bytes = await self._ws.receive_bytes()
  File "C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client_ws.py", line 281, in receive_bytes
    raise TypeError(
TypeError: Received message 257:None is not bytes

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py", line 76, in join_ladder_game
    result = await sc2.main._play_game(players[0], client, realtime, portconfig, step_time_limit, game_time_limit)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\main.py", line 238, in _play_game
    player_id = await client.join_game(
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\client.py", line 88, in join_game
    result = await self._execute(join_game=req)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\protocol.py", line 67, in _execute
    response = await self.__request(request)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\sc2\protocol.py", line 48, in __request
    sys.exit(2)
SystemExit: 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 15, in <module>
    result, opponentid = run_ladder_game(bot)
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py", line 67, in run_ladder_game
    result = asyncio.get_event_loop().run_until_complete(g)
  File "C:\Users\Manuel\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py", line 81, in join_ladder_game
    except ConnectionAlreadyClosed:
NameError: name 'ConnectionAlreadyClosed' is not defined

27-05-2020 09-27-32: Starting game vs VibuTerran
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py:85: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py:307: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x17694AA8>

27-05-2020 09-37-13: Starting game vs VibuTerran

27-05-2020 09-41-44: Starting game vs VibuTerran

27-05-2020 09-44-06: Starting game vs VibuTerran
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\helpers.py:107: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
  def noop(*args, **kwargs):  # type: ignore
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
C:\Users\Manuel\Desktop\Ladder\Bots\MavBot\__init__.py:85: RuntimeWarning: coroutine 'ClientWebSocketResponse.close' was never awaited
  ws_connection.close()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
C:\Users\Manuel\AppData\Roaming\Python\Python38\site-packages\aiohttp\client.py:307: ResourceWarning: Unclosed client session <aiohttp.client.ClientSession object at 0x17126A30>

27-05-2020 09-48-17: Starting game vs TheHarvester
